### ISSUE TITLE
Between clients and a server communication 

### ISSUE THREAD

**Issue by brutalremus** [Sound932/Chit-Chat#4]
hello, let's assume that the program is installed on the server. The users use the program using the shortcut. In this case, how will the users access the server. Where do I need to make changes?

**Comment by Ameer5121** [comment]
If you had downloaded it through the "Releases" page, and then you tried to connect but failed; that was because of electricity issues I had and are fixed now. If you try to login through the application that is officially released(In the releases page) now, you should be able to login.

However, if you're talking about setting up your own server that will work with **Chit Chat**, then I suggest you to head to https://github.com/Sound932/WebAPI-ChatHub. There are instructions there on how to setup the server. 

If you're still having troubles setting up the server, contact me on Discord(Sound#9535) and I'll assist you whenever free.

**Comment by brutalremus** [comment]
Currently the program works fine on my computer. But when I run the program from a different computer, I want to do it in real time (like chat). How do I let all users send requests to the same server with the help of Web sockets. I wanted to ask this. I hope I was able to explain.

**Comment by Ameer5121** [comment]
You have to use the server that is meant to be used with ChitChat which is https://github.com/Sound932/WebAPI-ChatHub.

If you setup the server according to the instructions in the "READ ME" page, everyone will be able to talk with each other in real-time.

**Comment by brutalremus** [comment]
Don't I need to advertise the server's ip address somewhere? I didn't see any place about it.

**Comment by Ameer5121** [comment]
On the server, no, you don't need to do that. It gets hosted on 0.0.0.0 which is whatever current IP address you're using. You don't need to change anything regarding the IP unless you want to other people to connect outside of LAN, in which case, you're going to have to port-forward the IP address, and then in ChitChat, you'd have to change where it says localhost to your public IP address. You don't need to do any of that if you're planning to just use inside of LAN only.

**Comment by brutalremus** [comment]
The system works fine on my own computer. However, other users in the same network cannot communicate with each other in real time. All sent messages are recorded in the database on the server.

**Comment by brutalremus** [comment]
Actually, what I don't understand is this: For example, there are 10 users and they want to message at the same time. Unfortunately, they can't text in real time. Do I need to make any changes for this? Maybe you're saying you don't need it.

**Comment by Ameer5121** [comment]
Can you clarify what you mean by "can't text in real time"? Are they able to login? Is there an exception? It should work fine if setup correctly.

**Comment by brutalremus** [comment]
I logged in from my own computer, no problem, I can write a message, it records to the database. But logging in from another computer, I can't see it on my own computer. Could I explain my problem?

**Comment by brutalremus** [comment]
I installed Chit Chat and Chatting Hub on two different computers on the same network. I logged in with different users from both, but these users cannot message each other. So everyone sees their own message. There is no real-time chat. If you want, you can try too, my dear friend.

**Comment by Ameer5121** [comment]
I just downloaded a fresh copy from https://github.com/Sound932/WebAPI-ChatHub and it worked fine. 2 users connected can talk to each other in real time.

Are you using IIS Express to run the server? If so, that might be the problem. Run the program using Kestrel only. Run the server where it says ChattingHub 
![image](https://user-images.githubusercontent.com/71935713/200939750-bbd150c1-11bf-4dbf-ad91-ef7e83836e3c.png)
